version: '3.8'

services:
  frontend:
    build:
      context: ./news-app 
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    environment:
      REACT_APP_BACKEND_URL: http://backend:8000 
    depends_on:
      - backend
    entrypoint: >
      sh -c "
      while ! curl -sf http://backend:8000/api/health; do
        echo 'Waiting for backend to be ready...';
        sleep 5;
      done;
      echo 'Backend is ready, starting frontend.';
      nginx -g 'daemon off;'
      "

  backend:
    build:
      context: ./news-aggregator 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./news-aggregator:/var/www
    environment:
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: news_aggregator
      DB_USERNAME: root
      DB_PASSWORD: 25971
      SCOUT_DRIVER: meilisearch
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_KEY: DQ3KpvVzIykfJo_Vr6xEnzmSiZISerJYbinlHwcliOA
    depends_on:
      - mysql
      - meilisearch
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: news_aggregator
      MYSQL_ROOT_PASSWORD: 25971
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  meilisearch:
    image: getmeili/meilisearch:latest
    command: ["meilisearch"]
    environment:
      MEILI_MASTER_KEY: DQ3KpvVzIykfJo_Vr6xEnzmSiZISerJYbinlHwcliOA
    ports:
      - "7700:7700"

volumes:
  db_data:
